server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: payment
          uri: http://localhost:8081
          predicates:
            - Path=/payments/** 
        - id: item
          uri: http://localhost:8082
          predicates:
            - Path=/items/**, /reviews/**, /check/**
        - id: reservation
          uri: http://localhost:8083
          predicates:
            - Path=/reservations/**
        - id: message
          uri: http://localhost:8084
          predicates:
            - Path=/messages/** 
        - id: viewpage
          uri: http://localhost:8085
          predicates:
            - Path= /itemviews/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/** 
        - id: item
          uri: http://item:8080
          predicates:
            - Path=/items/**, /reviews/**, /check/**
        - id: reservation
          uri: http://reservation:8080
          predicates:
            - Path=/reservations/**
        - id: message
          uri: http://message:8080
          predicates:
            - Path=/messages/** 
        - id: viewpage
          uri: http://viewpage:8080
          predicates:
            - Path= /itemviews/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080